apiVersion: v1  # Versión de la API
kind: Service   # Tipo de recurso
metadata:
  name: myapp-v1
  labels:
    app: myapp
    version: v1
spec:             # Especificaciones del servicio
  type: ClusterIP # Tipo de servicio
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: myapp
    version: v1