apiVersion: v1
kind: Service
metadata:
  name: myapp-v2
  labels:
    app: myapp
    version: v2
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: myapp
    version: v2